---
version: '3.8'
services:
    prep:
      build: ./prepare
      dockerfile: Dockerfile
      volumes:
        -  '.app'
    prod:
      build: ./run
      dockerfile: Dockerfile

volumes:
      shared_data:
... 