---
version: '3.8'
services:
    prep:
      build: 
          context: ./prepare
          dockerfile: Dockerfile
      volumes:
        -  shared_data:/output
      restart: 'no'
    prod:
      build: 
          context: ./run
          dockerfile: Dockerfile
      volumes: 
        - shared_data:/input
      depends_on: 
        - prep 
      ports: 
        - "8888:8080"
      restart: unless-stopped

volumes:
      shared_data: